---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp-deployment
  labels:
    app: myflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
        - name: myflaskapp
          image: docker.io/muthiendia/helloworld2:v1
          # imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 5000  
  selector:
    app: myflaskapp
  type: LoadBalancer